# Generated by Django 4.2.2 on 2023-08-14 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_description_alter_product_nomination'),
        ('users', '0002_alter_user_avatar_alter_user_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='продукт'),
            preserve_default=False,
        ),
    ]
