# Generated by Django 4.2.2 on 2023-08-20 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_is_active_alter_user_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('pk',), 'permissions': [('block_user', 'Block or unblock user')], 'verbose_name': 'Пользователь сервиса', 'verbose_name_plural': 'Пользователи сервиса'},
        ),
    ]
