# Generated by Django 4.2.2 on 2023-07-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('slug', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=150, verbose_name='Содержимое')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='картинка')),
                ('date_of_create', models.DateTimeField(verbose_name='Дата создания')),
                ('publication_type', models.BooleanField(verbose_name='Признак публикации')),
                ('views_count', models.IntegerField(verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
    ]
