# Generated by Django 4.2.2 on 2023-07-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='slug',
            field=models.CharField(max_length=50, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='material',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
