# Generated by Django 4.2.2 on 2023-08-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_description_alter_product_nomination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, unique=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nomination',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='наименование'),
        ),
    ]
