# Generated by Django 4.2.2 on 2023-08-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_control',
            field=models.BooleanField(default=True, verbose_name='признак версии'),
        ),
    ]
