# Generated by Django 4.2.2 on 2023-08-20 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_version_version_control'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ('pk',), 'permissions': [('block_version', 'Block or unblock version')], 'verbose_name': 'Версия', 'verbose_name_plural': 'Версии'},
        ),
    ]
